version: "3"
services:
  app:
    build: .
    restart: always
    environment:
      - APPHOST
      - APPPORT
      - APPURL
      - AUTH_STRATEGY
      - DBHOST
      - DBPORT
      - DOCSDB
      - DOCSHOST=${DOCSHOST:-mongo}
      - DOCSPORT
      - DOCS_ROOT_PASSWORD
      - LOGFILE
      - LOGLEVEL
      - NODE_ENV
      - OIDC_CLIENT_ID
      - OIDC_PROVIDER_URL
      - SESSION_SECRET
    depends_on:
      mongo:
        condition: service_healthy
      mysql:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${APPPORT:-3000}/health"]
      start_interval: 5s
      start_period: 30s
      interval: 120s
      timeout: 5s
      retries: 5
  mongo:
    build: docs
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: ${DOCS_ROOT_PASSWORD}
    volumes:
      - ./docs/data:/data/db
      # - mongo-data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      start_interval: 5s
      start_period: 30s
      interval: 60s
      timeout: 5s
      retries: 5
  mysql:
    build: db
    command: --default-authentication-plugin=mysql_native_password
    # command: --mysql-native-password=ON
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - ./db/data:/var/lib/mysql
    healthcheck:
      test: 'mysql -p${DB_ROOT_PASSWORD} -h localhost -e "SELECT 1+1 as result" &> /dev/null'
      start_interval: 5s
      start_period: 30s
      interval: 60s
      timeout: 5s
      retries: 5
  nginx:
    build: nginx
    restart: always
    ports:
      - "${NGINX_PORT:-443}:443"
    depends_on:
      - app
      - mongo
      - valkey
  valkey:
    build: keyval
    restart: always
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    restart: always
  grafana:
    image: grafana/grafana:latest
    volumes:
      - ./grafana/data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    restart: always
    depends_on:
      - prometheus
  nginx-exporter:
    image: nginx/nginx-prometheus-exporter:latest
    command: -nginx.scrape-uri=http://nginx/nginx_status
    depends_on:
      - nginx
  # mongodb-exporter:
  #   image: bitnami/mongodb-exporter:latest
  #   environment:
  #     MONGODB_URI: mongodb://admin:${DOCS_ROOT_PASSWORD}@${DOCSHOST:-mongo}:${DOCSPORT:-27017}/admin?authMechanism=SCRAM-SHA-256
  #   restart: always
  #   depends_on:
  #     - mongo
  # mysqld-exporter:
  #   image: prom/mysqld-exporter:latest
  #   command:
  #     # need to find a way to pass the config file
  #     - "--config.my-cnf=/etc/my.cnf"
  #   environment:
  #     DATA_SOURCE_NAME: root:${DB_ROOT_PASSWORD}@tcp(${DBHOST:-localhost}:${DBPORT:-3306})/
  #   ports:
  #     - "9104:9104"
  #   restart: always
  #   depends_on:
  #     mysql:
  #       condition: service_healthy

  # These will not work on MacOS
  # node-exporter:
  #   image: prom/node-exporter:latest
  #   ports:
  #     - "9100:9100"
  #   restart: always
  #   command:
  #     - '--path.rootfs=/host'
  #   volumes:
  #     - /:/host:ro,rslave
  # cadvisor:
  #   image: gcr.io/google-containers/cadvisor:latest
  #   ports:
  #     - "8080:8080"
  #   restart: always
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock:ro
  #     - /sys:/sys:ro
  #     - /var/lib/docker/:/var/lib/docker:ro

# volumes:
#   mongo-data:
