version: "3"
services:
  app:
    build: .
    restart: always
    environment:
      APPHOST: ${APPHOST}
      APPPORT: ${APPPORT}
  nginx:
    build: nginx
    restart: always
    environment:
      NGINX_PORT: ${NGINX_PORT:-443}
    ports:
      - "${NGINX_PORT}:443"
    depends_on:
      - app

